<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>indonesia jaya</title>
</head>

<body>
   <p>Penulis: Dr. Ferry Hadary, M. Eng.</p>
<p>Proses belajar mengajar adalah inti aktivitas dalam pendidikan. Proses ini terjadi antara dosen dan mahasiswa serta dipengaruhi oleh hubungan yang ada dalam proses tersebut. Ini menyebabkan metode belajar mahasiswa juga dipengaruhi oleh metode pengajaran dari dosennya. Seiring dengan pesatnya perkembangan di dunia telekomunikasi yang ditandai dengan era digitalisasi, khususnya di bidang teknologi informasi dan komunikasi (TIK), tentunya proses belajar mengajar juga menuntut adanya penyesuaian atau linearitas institusi pendidikan dalam penggunaan metode proses belajar mengajar.</p>
<p>Adanya realita tersebut, perguruan tinggi jelas memerlukan sarana dan prasarana TIK untuk menunjang kegiatan Tri Dharma sehingga dapat menjawab tantangan-tantangan yang ada, khususnya untuk peningkatan kualitas proses belajar mengajar. Konsep pendidikan yang semakin berkembang dan banyak diadopsi belakangan ini adalah berbasis pada learning approach dan sedikit demi sedikit meninggalkan format sebelumnya yang berbasis teaching approach. Pada konsep learning approach penyampaian ilmu pengetahuan, dan juga termasuk proses pembelajaran adalah berbasis multimedia dan elektronik. Konsep ini kemudian dikenal dengan sebutan e-learning yang membawa pengaruh terjadinya proses transformasi pendidikan konvensional ke dalam bentuk digital, baik secara isi (content) maupun sistemnya.     Konsep ini menjadi alternatif yang sepadan dengan konsep teaching approach yang berbasis kampus.</p>
<p>Conventional Learning dan e-Learning</p>
<p>Menyikapi perkembangan TIK tersebut menyebabkan adanya perubahan metode konvensional dalam proses belajar mengajar yang digantikan dengan metode e-learning. Metode conventional learning yang mengharuskan dosen dan mahasiswa harus bertatap muka langsung di ruangan kelas memiliki beberapa ciri, yaitu: 1) pembelajaran tergantung pada dosen; 2) seluruh kegiatan belajar mengajar terpusat di kampus; 3) dosen merupakan sumber ilmu; 4) dibatasi jarak, ruang dan waktu; dan 5) harus memiliki sarana dan prasarana belajar mengajar yang memadai serta sdm dosen yang memahami setiap materi kuliah yang akan diajarkan. Sedangkan ciri-ciri e-learning adalah: 1) pembelajaran tidak tergantung kepada dosen; 2) banyaknya sumber materi dan kemudahan akses; 3) peran dosen hanya sebagai mediator atau pembimbing; 4) proses belajar tidak terkendala jarak, ruang dan waktu.</p>
<p>Merujuk dari ciri-ciri kedua metode di atas, maka nge-blog adalah sebuah alternatif metode proses belajar mengajar yang bersifat e-learning dan juga student centered. Perguruan tinggi yang ingin menggunakan TIK untuk penerapan e-learning biasanya menggunakan Learning Management System (LMS) untuk menyediakan virtual classroom (ruang kelas virtual) di internet. Virtual classroom yang dimiliki biasanya memiliki banyak metafora ruang kelas konvensional seperti forum diskusi, pengumpulan tugas, katalog/perpustakaan bahan ajar, katalog hyperlink dan lain sebagainya.</p>
<p>Haruskah Dosen nge-Blog?</p>
<p>Jika pertanyaan tersebut diajukan, maka jawaban atas pertanyaan tersebut sesungguhnya telah tergambar jelas pada sebuah acara seminar. Selain untuk peningkatan proses belajar mengajar, "keharusan" dosen untuk nge-blog juga didasari pada beberapa alasan yang dirangkum oleh Yuyun Estriyanto (2008) dalam sebuah tulisan. Menurut pandangannya, nge-blog itu adalah untuk alasan sebagai berikut: 1) personal branding, 2) soft marketing, 3) mengenalkan core kompetensi kepada publik, 4) memberikan pencerahan pemikiran kepada masyarakat.</p>
<p>Dari sejumlah alasan tersebut, butir 1 sampai dengan 3 pada intinya sama dan saling berkaitan. Personal branding dibutuhkan untuk pembentukan citra diri. Hal ini dilakukan untuk mengenalkan core kemampuan dosen tersebut kepada masyarakat. Tujuannya apa? Menjual diri, menjual profesionalitas. Ketika telah ditanamkan kepada masyarakat bahwa dosen tersebut adalah ahli dalam suatu bidang, maka dengan sendirinya jika memerlukan tenaga ahli pada bidang tersebut maka dosen itu yang akan dipercaya untuk melakukan pekerjaan tersebut. Sedangkan pada butir ke-4, sebenarnya dilandasi dari suatu image yang ada pada masyarakat bahwa dosen adalah profesi dengan strata sosial tinggi di masyarakat. Bukan pada kemampuan finansialnya, melainkan pada kompetensi akademiknya atau intelektualitasnya. Oleh karena itu, sangat pantas jika dosen seharusnya bisa memberikan sumbang pemikiran mengenai kondisi sosial masyarakat dalam berbagai aspek kehidupan berdasarkan pada latar belakang keilmuan yang dimilikinya.</p>
<p>Fungsi Blog dalam Sistem Terintegrasi</p>
<p>Jika dosen sudah memiliki blog, maka bagaimanakah mengintegrasikannya dalam proses belajar mengajar? Ada beberapa cara, diantaranya para dosen dapat menggunakan blog untuk menampilkan informasi perkuliahan yang diampu, bahan ajar yang siap diunduh mahasiswa, daftar hyperlink sebagai referensi, memberikan tugas dan menampilkan hasil penelitan dosen. Karena fitur pada blog memungkinkan memberikan pertanyaan dan komentar atas artikel atau bahan ajar yang tersedia, maka komunikasi pun akan berjalan dua arah dan interaktif, baik dari dosen ke mahasiswa dan juga sebaliknya.</p>
<p>Cara yang lain adalah ketika memberikan tugas kepada mahasiswa, maka dosen tersebut menerangkannya secara lisan dan kemudian menampilkannya pada blog. Mahasiswa yang akan mengumpulkan tugas diminta untuk menampilkan jawaban dari tugas dalam blog pribadi mahasiswa tersebut. Penilaian diberikan dengan cara dosen tersebut mengunjungi blog mahasiswa untuk kemudian memberikan komentar tentang jawaban tugas yang telah dibuat mahasiswa. Cara ini memberikan arti bahwa mahasiswa tidak hanya bertanggung jawab atas jawaban tugas kepada dosen saja, melainkan bertanggung jawab pula kepada publik/pengguna internet sebagai pembaca.</p>
<p>Integrasi blog dalam aktifitas proses belajar mengajar seperti ini secara otomatis meningkatkan waktu "tatap muka" dosen dan mahasiswa. Diskusi yang terekam dalam fasilitas komentar yang tersedia pada blog juga dapat menjadi referensi tambahan bagi para pembaca blog dan dapat dilihat serta dibaca kapan saja. Selain mendidik dan mengenalkan mahasiswa menulis melalui media internet, cara-cara ini juga mampu mendongkrak nama institusi pendidikan di dunia maya serta melatih mahasiswa untuk berbagi ilmu dengan orang lain.</p>
<p>Ketika membicarakan blog dalam sebagai suatu sub-sistem yang terintegrasi, maka akan ada pula beberapa sub-sistem yang saling berkaitan serta saling memengaruhi. Proses belajar mengajar merupakan sebuah input dan output yang diharapkan adalah proses belajar mengajar yang berkualitas. Tentunya sistem tersebut harus memiliki karakteristik sebagai sistem yang memiliki umpan balik (feedback system). Fungsi Pusat Penjamin Mutu (PPM) baik di tingkat fakultas bahkan universitas diharapkan dapat menjamin mutu atau kualitas dari proses belajar mengajar yang dihasilkan. Tentunya objek yang akan dikendalikan, atau disebut plant adalah content yang ada pada blog tersebut. Konsep ini juga menjelaskan bahwa blog yang merupakan salah salah satu sub-sistem sebenarnya digerakkan (actuator) oleh dosen dan mahasiswa selaku pelaku aktivitas proses belajar mengajar. Sedangkan kurikulum yang berbasis pada capaian rumusan kompetensi merupakan pengendalinya (controller).</p>
<p>Dengan adanya integrasi antar sub-sistem tersebut diharapkan  akan menghasilkan proses belajar mengajar yang tidak hanya melibatkan dosen, tetapi juga mahasiswa, untuk menghasilkan proses belajar mengajar yang lebih berkualitas. Oleh karena itu, adakah alasan seorang dosen untuk tidak segera memulai nge-blog?</p>
<p>*Penulis adalah dosen di Jurusan Teknik Elektro, Fakultas Teknik, Universitas Tanjungpura.</p>
                                                

</body>
</html>